import type { Metadata } from "next";
import { Montserrat} from "next/font/google";
import "./globals.css";
import {Navbar} from "@/components/layout/navbar";
import { Footer } from "@/components/layout/footer";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-mont"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className= {montserrat.className}
      >
        <Navbar></Navbar>
        <main> {children} </main>
        <Footer></Footer>
        
      </body>
    </html>
  );
}
